export default {
    backicn:require("../assets/Images/backImg.jpg"),
    Profileicn:require("../assets/Images/profilePic.jpg"),
    bellIcn:require("../assets/Images/bell.png"),
    hairImg:require("../assets/Images/hair.webp"),
    LidaIMg:require("../assets/Images/Lidamila.jpg"),
    CoraImg:require("../assets/Images/corabelle.jpg"),
    msgImg:require("../assets/Images/message.png"),
    carRepair:require("../assets/Images/CarRepair.jpg"),
    nailPaint:require("../assets/Images/nailPaint.webp"),
    face:require("../assets/Images/Face.png"),
    delete:require("../assets/Images/delete.png"),
    edit:require("../assets/Images/edit.png"),
    home:require("../assets/Images/home.png"),
    booking:require("../assets/Images/booking.png"),
    chats:require("../assets/Images/chat.png"),
    account:require("../assets/Images/person.png"),
    dropdown:require("../assets/Images/DropDown.png")
}